name: release binaries

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release-binaries:
    name: release binaries linux/windows/android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, android, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: 386
            goos: android
          - goarch: amd64
            goos: android
          - goarch: arm64
            goos: windows
          - goarch: 386
            goos: darwin
            
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.48
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.22"
        pre_command: "rm gui.go"
        ldflags: "-w -s"
        md5sum: FALSE
